# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Required', max_length=250)),
                ('email', models.EmailField(help_text='Required', max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
