# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-26 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='ticket_class',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='survived',
            new_name='s',
        ),
    ]
