# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('manager_emp_id', models.CharField(max_length=100, null=True)),
                ('asset_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('manager_emp_id', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('billed_assets', models.IntegerField(max_length=4, null=True)),
                ('budget', models.CharField(max_length=50, null=True)),
                ('partner', models.CharField(max_length=200, null=True)),
                ('sales_person_id', models.CharField(max_length=1000, null=True)),
                ('paid', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
