# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.CharField(max_length=510)),
                ('task_type', models.CharField(max_length=510, null=True)),
                ('billed_hours', models.CharField(max_length=510, null=True)),
                ('task_description', models.CharField(max_length=510, null=True)),
                ('isapproved', models.CharField(max_length=510, null=True)),
                ('last_updated', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbo.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='billed_assets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='projectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbo.Project'),
        ),
    ]
