# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0002_auto_20190828_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved_by_emp_id',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='emp_id',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
