# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0003_auto_20190829_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='projectid',
            new_name='project',
        ),
    ]
