# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0005_auto_20190829_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
