# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0006_auto_20190829_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbo.Project'),
        ),
    ]
