# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0010_auto_20190829_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
