# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-29 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='project',
            new_name='projectid',
        ),
    ]
