# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0005_timesheet_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='task_type',
        ),
    ]
