# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0007_timesheet_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='bill_date',
            field=models.DateField(),
        ),
    ]
