# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0008_auto_20190830_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.EmailField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_emp_id',
            field=models.EmailField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
