# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0009_auto_20190830_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='task_type',
            field=models.CharField(max_length=510, null=True),
        ),
    ]
