# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-31 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0010_auto_20190830_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=400)),
            ],
        ),
    ]
